language: go

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  global:
    - ARTIFACT_PATH="https://api.bintray.com/content/gilmour/gilmour-tools/ignore_host"

go: tip

script:
  - go build -o redis_pop main.go

after_success:
  - curl -T redis_pop -umeson10:$BINTRAY_KEY $ARTIFACT_PATH/$GIMME_OS_$GIMME_ARCH/$TRAVIS_JOB_NUMBER/ignore_host
  - curl -T redis_pop -umeson10:$BINTRAY_KEY $ARTIFACT_PATH/$GIMME_OS_$GIMME_ARCH/latest/ignore_host
  - curl -XPOST -umeson10:$BINTRAY_KEY $ARTIFACT_PATH/$GIMME_OS_$GIMME_ARCH/$TRAVIS_JOB_NUMBER/publish
  - curl -XPOST -umeson10:$BINTRAY_KEY $ARTIFACT_PATH/$GIMME_OS_$GIMME_ARCH/latest/publish
