language: go

go:
  - tip

services:
  - redis-server

env:
  - GIMME_OS=linux GIMME_ARCH=amd64 ARTIFACT_PATH="https://api.bintray.com/content/gilmour/gilmour-tools/ignore_host/linux_64"
  - GIMME_OS=darwin GIMME_ARCH=amd64 ARTIFACT_PATH="https://api.bintray.com/content/gilmour/gilmour-tools/ignore_host/darwin_64"


go: tip

script:
  - go test -v ./...
  - go build -o redis_pop main.go

after_success:
  - curl -T redis_pop -umeson10:$BINTRAY_KEY $ARTIFACT_PATH/$TRAVIS_JOB_NUMBER/ignore_host
  - curl -T redis_pop -umeson10:$BINTRAY_KEY $ARTIFACT_PATH/latest/ignore_host
  - curl -XPOST -umeson10:$BINTRAY_KEY $ARTIFACT_PATH/$TRAVIS_JOB_NUMBER/publish
  - curl -XPOST -umeson10:$BINTRAY_KEY $ARTIFACT_PATH/latest/publish
